import fs from 'node:fs/promises';
import path from 'node:path';

const THUMB_SUFFIX = '-640.webp';
const IMAGE_FILE_RE = /\.(jpe?g|png|webp|avif)$/i;

/** Image folders exposed in the admin media library, in display order. */
const LIBRARY_FOLDERS = [
  { dir: 'media', group: 'fleet' },
  { dir: 'whatsapp_images_cropped/interior', group: 'interiors' },
  { dir: 'whatsapp_images_cropped/rear', group: 'rear' },
  { dir: 'whatsapp_images_cropped/detail', group: 'details' },
  { dir: 'whatsapp_images_cropped/main', group: 'main' },
  { dir: 'uploads', group: 'uploads' },
  { dir: 'whatsapp_images', group: 'posters' },
];

async function walk(dir) {
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch (err) {
    if (err.code === 'ENOENT') return [];
    throw err;
  }
  const nested = await Promise.all(
    entries.map((entry) => {
      const full = path.join(dir, entry.name);
      return entry.isDirectory() ? walk(full) : [full];
    }),
  );
  return nested.flat();
}

/**
 * Knows which images exist under /public and which have a pre-rendered
 * 640px thumbnail (generated by scripts/build-media.py).
 */
export function createMediaLibrary(publicDir) {
  let thumbs = new Map();
  const toWebPath = (file) => encodeURI(`/${path.relative(publicDir, file).split(path.sep).join('/')}`);

  async function refresh() {
    const files = await walk(path.join(publicDir, 'media'));
    thumbs = new Map(
      files
        .filter((file) => file.endsWith(THUMB_SUFFIX))
        .map((file) => {
          const thumb = toWebPath(file);
          return [`${thumb.slice(0, -THUMB_SUFFIX.length)}.webp`, thumb];
        }),
    );
  }

  const withThumbs = (images) => images.map((src) => ({ src, thumb: thumbs.get(src) ?? src }));

  async function list() {
    const items = [];
    for (const { dir, group } of LIBRARY_FOLDERS) {
      const files = await walk(path.join(publicDir, dir));
      for (const file of files.sort()) {
        if (!IMAGE_FILE_RE.test(file) || file.endsWith(THUMB_SUFFIX)) continue;
        const src = toWebPath(file);
        items.push({ src, thumb: thumbs.get(src) ?? src, group });
      }
    }
    return items;
  }

  return { refresh, withThumbs, list };
}
